# Generated by Django 4.2 on 2023-04-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_band_year_formed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='year_formed',
        ),
    ]
