# Generated by Django 4.2 on 2023-04-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_year_formed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='year_formed',
            new_name='year_forme',
        ),
    ]
