# Generated by Django 4.2 on 2023-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_band_active_remove_band_biography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Band',
        ),
    ]
